on: [push]

name: Rotate API Keys

jobs:
  rotate-keys:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Rotate API Keys
        uses: azure/CLI@v1
        with:
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/keyrotator.sh
            $GITHUB_WORKSPACE/keyrotator.sh '$SUBSCRIPTION_NAME' '$RESOURCE_GROUP_NAME' 'apikey' '${{ secrets.KEY_VAULT_NAME }}' '$API_KEY_SECRET_NAME'   
